services:
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:9.7
    environment:
        SCRIPT_NAME: ${SCRIPT_NAME:-/}
        PGADMIN_CONFIG_SERVER_MODE: 'False'
    env_file:
      - ../vault-agent/vault_secrets/pgadmin/.env
    volumes:
        - pgadmin-data:/var/lib/pgadmin
    networks:
      - backend-network
    restart: unless-stopped

volumes:
  pgadmin-data:

networks:
  backend-network:
    external: true
    