services:
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:9.7
    environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@example.com}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
        SCRIPT_NAME: ${SCRIPT_NAME:-/}
        PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
        - pgadmin-data:/var/lib/pgadmin
    networks:
      - backend-network
    restart: unless-stopped

volumes:
  pgadmin-data:

networks:
  backend-network:
    external: true
    