version: "3.9"

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/test/Dockerfile
    ports:
      - '80:80'
    volumes:
      - ./logs/test/nginx:/var/log/nginx
      - ./files/html/:/etc/nginx/html/
      - ./files/nginx.test.conf:/etc/nginx/nginx.conf
      - ../website/app/dist:/usr/share/website/dist:ro
    restart: always
    environment:
      - TZ=Europe/Moscow
    networks:
      - backend-network

networks:
  backend-network:
    external: true
