version: "3.9"

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./logs/dev/nginx:/var/log/nginx
      - ./files/certs/:/etc/nginx/certs/
      - ./files/html/:/etc/nginx/html/
      - ./files/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    environment:
      - TZ=Europe/Moscow
    networks:
      - backend-network

networks:
  backend-network:
    external: true
