services:
  vault:
    image: hashicorp/vault:1.20.3
    container_name: vault_container
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    command: "server -dev -dev-root-token-id=root"
    volumes:
      - vault_data:/vault/file
      - ./vault-init.sh:/vault-init.sh
    cap_add:
      - IPC_LOCK
    entrypoint: ["/vault-init.sh"]
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://127.0.0.1:8200/v1/sys/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - backend-network

volumes:
  vault_data:

networks:
  backend-network:
    external: true
