export const WEBSOCKET_URL = import.meta.env.VITE_WEBSOCKET_URL;

export const USER_WEBSOCKETS_NAMESPACE = import.meta.env.VITE_USER_WEBSOCKETS_NAMESPACE || "";
export const USER_WEBSOCKET_HANDSHAKE_PATH = import.meta.env.VITE_USER_WEBSOCKET_HANDSHAKE_PATH;

export const TAP_GOOSE_WEBSOCKETS_NAMESPACE = import.meta.env.VITE_TAP_GOOSE_WEBSOCKETS_NAMESPACE || "";
export const TAP_GOOSE_WEBSOCKET_HANDSHAKE_PATH = import.meta.env.VITE_TAP_GOOSE_WEBSOCKET_HANDSHAKE_PATH;

export const CHAT_WEBSOCKETS_NAMESPACE = import.meta.env.VITE_CHAT_WEBSOCKETS_NAMESPACE || "";
export const CHAT_WEBSOCKET_HANDSHAKE_PATH = import.meta.env.VITE_CHAT_WEBSOCKET_HANDSHAKE_PATH;
