services:
  website:
    container_name: goose-web-dev
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    env_file:
      - ./docker/dev/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    restart: always
    networks:
      - backend-network

networks:
  backend-network:
    external: true