version: '3'

services:
  website:
    container_name: web-dev
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    env_file:
      - ./docker/dev/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '3000:3000'
    volumes:
      - ./app:/app
    restart: always
    networks:
      - backend-network

networks:
  backend-network:
    external: true